version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8002:8002"
#    depends_on:
#      - db
#    environment:
#      - MONGO_URL=mongodb://db:27017
#      - MONGO_PASSWORD=
#      - MONGO_USER=
#      - MONGO_DATABASE=

#  db:
#    image: mongo:6.0
#    container_name: mongodb_container
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./data:/data/db
